AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi
Globals:
  Function:
    Runtime: java21
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 60 #seconds not milliseconds
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.ratna.aws.lambda.apis.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy: 
            TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
          Type: Api
          Properties: 
            Path: /orders
            Method: POST
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.ratna.aws.lambda.apis.ReadOrderLambda::readOrder
      Policies:
        - DynamoDBReadPolicy: 
            TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
          Type: Api
          Properties: 
            Path: /orders
            Method: GET
Outputs:
  CreateOrderAPI:
    Description: "API Gateway endpoint url for create order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CreateOrderFunction: 
    Description: "Create Order Lamda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole: 
    Description: "Create Order Lamda Function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn

